### PR TITLE
Misc updates

### LINKED ISSUE #172: How can I use isSimple() method?
- question 1:

I am using version 4.1.0, Swift 4.2

I hope I can use this method： isSimple. to judge a polygon

As I understand it, I added a method in extension Geometry:

```
// in SpatialAnalysis.swift file
public extension Geometry {
  func isSimple() -> Bool {
        let result =  GEOSisSimple_r(GEOS_HANDLE, self.storage.GEOSGeom)
        assert(result != 2, "GEOSisSimple_r on exception")
        return result == 1
    }
}
```

but alway return true，Can you give me some advice?

In addition, The problem may be：
```
// in Polygon.cpp file

bool
Polygon::isSimple() const
{
	return true;
}
```

 - question 2:

I hope to contribute to this project. Is there any step?

### LINKED ISSUE #180: Update Feature.init to take GeometryConvertible instead of Geometry
This will make it more convenient to use. See GeometryCollection for an example.

### LINKED ISSUE #183: Use ~> operator when specifying geos dependency in podspec
This will allow propagation of the fix for https://github.com/GEOSwift/geos/issues/9

### PR DESCRIPTION
**Pull request by macdrevx**
* Add isEmpty, isRing, isClosed, and isSimple (Fixes #172)
* Update Feature.init to take GeometryConvertible (Fixes #180)
* Use `~>` to specify geos version requirement (Fixes #183)

### CODE REVIEW

File: GEOSwiftTests/GEOS/SimplicityTestableTests.swift [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+
+        XCTAssertTrue(try multiPoint.isSimple())
+
+        multiPoint.points += multiPoint.points
+
+        XCTAssertFalse(try multiPoint.isSimple())
+    }
+
+    func testIsSimpleAllTypes() {
+        for g in simplicityTestables {
```
Comment (joshuapuentetransloc) [inline GEOSwiftTests/GEOS/SimplicityTestableTests.swift]: Does g stand for geometry?

Comment (macdrevx) [reply GEOSwiftTests/GEOS/SimplicityTestableTests.swift]: Yep. In similar tests, this reads `for g in geometryConvertibles {`

I should probably make it `s` for these tests.
